# Generated by Django 3.2.7 on 2021-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crudEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='', max_length=100)),
                ('emp_age', models.IntegerField()),
                ('emp_phone', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(default='', max_length=1)),
                ('salary', models.FloatField(default=0)),
            ],
        ),
    ]
